name: rent_a_cars
description: A new Flutter project.

# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_screenutil: ^5.5.4
  google_fonts: ^3.0.1


flutter:

  uses-material-design: true
  
  assets:
    - assets/tesla/
    - assets/audi/
    - assets/chevrolet/
    - assets/mers/
    - assets/lamborghini/
    - assets/lexus/
    - assets/kia/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
 