List imageAssets = [
  [
    'assets/tesla/1.png',
    'assets/tesla/2.png',
    'assets/tesla/3.webp',
    'assets/tesla/4.webp',
  ],
  [
    'assets/audi/1.png',
    'assets/audi/2.png',
    'assets/audi/3.png',
    'assets/audi/4.png',
  ],
  [
    'assets/mers/1.png',
    'assets/mers/2.png',
    'assets/mers/3.webp',
    'assets/mers/4.png',
  ],
  [
    'assets/chevrolet/1.png',
    'assets/chevrolet/2.png',
    'assets/chevrolet/3.webp',
    'assets/chevrolet/4.png',
  ],
  [
    'assets/lamborghini/1.png',
    'assets/lamborghini/2.png',
    'assets/lamborghini/4.png',
    'assets/lamborghini/3.png',
  ],
  [
    'assets/lexus/1.png',
    'assets/lexus/2.png',
    'assets/lexus/3.png',
    'assets/lexus/4.png',
  ],
  [
    'assets/kia/1.png',
    'assets/kia/2.png',
    'assets/kia/3.png',
    'assets/kia/4.png',
  ],
];
